Allow Allocation
Hejsil/mecha pull request #22
Opened 2021-02-20 20:42 UTC by erooke

Attempts to address #21 
- Makes all parsers return `mecha.Error!Result` instead of `Result`: 
    ```zig
    Error = error{ParserFailed, OtherError} || mem.Allocator.Error
    ```
  `error.ParserFailed` is treated as `null` was previously. Other errors are simply allowed to bubble up as mecha can't do anything about them.
- All parsers are now of the signature `fn(*mem.Allocator, []const u8) Error!Result(T)`
  - All the old tests were updated to feed the parser a `FailingAllocator` to preserve the information that they shouldn't allocate. 
- Convert now takes a function of type `fn( *mem.Allocator, ParserResult(parser)) !T` if `conv` returns an error in the `mecha.Error` error set it is returned else `error.OtherError` is returned.
  - The built in convert functions all return `error.ParseFailed` on failure to convert as this was the old behavior.   

Making `manyN`, `manyRange`, and `many` allocate the result of what they parse is not addressed.

2021-02-21 14:35 UTC, Hejsil requested changes
Mostly good. I have some cosmetic changes and there is one bug that needs fixing

2021-02-21 14:35 UTC, Hejsil commented on mecha.zig
> +            };
No reasons for having a block for the catch.
```zig
            const r = parser(allocator, str) catch |e| switch (e) {
                error.ParserFailed => return Res.init(null, str),
                else => return e,
            };
```

2021-02-21 14:35 UTC, Hejsil commented on mecha.zig
> +                }
No wrapping block :)
```zig
                } else |e| switch (e) {
                    error.ParserFailed => {},
                    else => return e,
                }
```

2021-02-21 14:35 UTC, Hejsil commented on mecha.zig
> +            };
Uuuh, I like this idea of converting any none mecha error into `OtherError`. I think an argument could be made that it is a little bit magical, but I think it is worth it in this case :+1: 

```zig
            const v = conv(allocator, r.value) catch |e| switch (@as(anyerror, e)) {
                error.ParserFailed => return error.ParserFailed,
                error.OutOfMemory => return error.OutOfMemory,
                else => return error.OtherError,
            };
```

2021-02-21 14:35 UTC, Hejsil commented on mecha.zig
> +        return unicode.utf8Decode(str[0..cp_len]);
Hmm, idk if we should return `ParserFailed` or not for `utf8Decode`.

2021-02-21 14:35 UTC, Hejsil commented on src/ascii.zig
> +            }
:)
```zig
            _ = parser(allocator, str) catch |e| switch (e) {
                error.ParserFailed => return Res.init(str[0], str[1..]),
                else => return e,
            };
            return error.ParserFailed;
```

2021-02-21 14:35 UTC, Hejsil commented on src/ascii.zig
> +}
We can use the `std.testing.failing_allocator` instead of having this function. Also this function invokes undefined behavior if `alloc` was ever called on the result, because the `Allocator` interface is copied out of the implementation here.

2021-02-21 14:35 UTC, Hejsil commented on src/utf8.zig
> +            }
:)
```zig
            } else |e| switch (e) {
                error.ParserFailed => {},
                else => return e,
            }
```

2021-02-21 14:35 UTC, Hejsil commented on src/utf8.zig
> +}
Again here, lets use `testing.failing_allocator` instead.

2021-02-21 14:35 UTC, Hejsil commented on mecha.zig
> +}
Saw this a little late. See my comment further down about `failingAllocator`.

2021-02-21 14:36 UTC, Hejsil commented on mecha.zig
> +}
Ooh, github orders the review comments based on when I wrote them lol

2021-02-21 20:38 UTC, erooke commented on src/ascii.zig
> +}
Ah cool, didn't know that existed :)

2021-02-21 20:40 UTC, erooke commented on mecha.zig
> +            };
Ah yeah, didn't even think about that. It's been changed.

2021-02-21 20:45 UTC, erooke commented on mecha.zig
> +        return unicode.utf8Decode(str[0..cp_len]);
Ah I meant to have this return `ParserFailed` as that preserves the old behavior more accurately. Although I realize that we couldn't have signaled it any other way before. I've updated it to return `ParserFailed`, but don't feel strongly one way or the other.

2021-02-21 21:04 UTC, Hejsil requested changes
A few more things

2021-02-21 21:04 UTC, Hejsil commented on README.md
> +    var allocator = std.testing.allocator;
I see a lot of `var allocator` here. They can all be `const`
```
    const allocator = std.testing.allocator;
```

2021-02-21 21:04 UTC, Hejsil commented on src/ascii.zig
> +///
Empty doc comment. Let's remove that

2021-02-21 21:18 UTC, erooke commented on README.md
> +    var allocator = std.testing.allocator;
Alright, changed all the allocators to const

2021-02-21 21:18 UTC, erooke commented on src/ascii.zig
> +///
lol, zig.vim being too clever for me. Fixed.

2021-02-22 15:10 UTC, data-man commented
Sorry, I don't like this. Personally for me, parsing without allocations is the most important feature of mecha. We need to find a better way.

2021-02-22 16:18 UTC, Hejsil commented
> Sorry, I don't like this. Personally for me, parsing without allocations is the most important feature of mecha. We need to find a better way.

All existing parsing code will still not do any allocation and it will be pretty straight forward to avoid allocation for people who don't want it (just pass a failing allocator to your parser). Aallocators are for the parsers that actually need allocation to work, such as most recursive parsers that construct trees. It will also allows us to have a version of `many` which actually collects the results instead of just returning the parsed string (which would most likely need to be reparsed). Do you have any specific reason in mind as to why we should not have the option to allocate memory?

2021-02-23 15:40 UTC, Hejsil commented
@data-man Wonna elaborate? Otherwise I would like to get this merged.

2021-02-23 16:41 UTC, data-man commented
@Hejsil 
I'm working on benchmarks. It doesn't take much time.

2021-02-23 17:38 UTC, data-man commented
```zig
const std = @import("std");

usingnamespace @import("mecha.zig");

const Rgb = struct {
    r: u8,
    g: u8,
    b: u8,
};

fn toByte(v: u8) u8 {
    return v * 0x10 + v;
}

fn toByte2(v: [2]u8) u8 {
    return v[0] * 0x10 + v[1];
}

const hex = convert(u8, toInt(u8, 16), asStr(ascii.digit(16)));
const hex1 = map(u8, toByte, hex);
const hex2 = map(u8, toByte2, manyN(2, hex));
const rgb1 = map(Rgb, toStruct(Rgb), manyN(3, hex1));
const rgb2 = map(Rgb, toStruct(Rgb), manyN(3, hex2));
const rgb = combine(.{
    ascii.char('#'),
    oneOf(.{
        rgb2,
        rgb1,
    }),
});

pub fn main() anyerror!void {
    const loops = 100_000_000;

    var n: usize = 0;

    const allocator = std.heap.page_allocator;
    const start = std.time.nanoTimestamp();

    while (n < loops) : (n += 1) {
        const a = rgb("#aabbcc").?.value;
        // const a = (try rgb(allocator, "#aabbcc")).value;
        std.math.doNotOptimizeAway(a);
    }
    const end = std.time.nanoTimestamp();
    const stdout = std.io.getStdOut().writer();

    try stdout.print("{} ns\n", .{(end - start)});
}
```
`$ zig build-exe -O ReleaseFast benchmark.zig`

My results:
`64 ns` master branch
`89 ns` this PR

2021-02-23 18:01 UTC, Hejsil commented
Something is wrong with this benchmark. Played around with it a little bit, incrementing the `loops` counter. At `10_000_000_000_000_000_000` the program still finishes instantly, while at `20_000_000_000_000_000_000` the program does not finish within a time-frame I am patient enough to wait for.

Even if the benchmark is correct, doing different runs gives different results which are `+-50ns`. That is very inconsistent.

2021-02-23 18:06 UTC, erooke commented
I don't think this benchmark shows what you want it too.  Running it multiple times shows that whatever it is doing is within the noise I would expect on a machine. 
```
Alloc
-----
1: 51 ns
2: 90 ns
3: 90 ns
4: 91 ns
5: 90 ns

Master
------
1: 71 ns
2: 40 ns
3: 90 ns
4: 90 ns
5: 90 ns
```

2021-02-23 18:17 UTC, Hejsil commented
Update. Ok, got the benchmark to behave.
```zig
const std = @import("std");

usingnamespace @import("mecha.zig");

const Rgb = struct {
    r: u8,
    g: u8,
    b: u8,
};

fn toByte(v: u8) u8 {
    return v * 0x10 + v;
}

fn toByte2(v: [2]u8) u8 {
    return v[0] * 0x10 + v[1];
}

const hex = convert(u8, toInt(u8, 16), asStr(ascii.digit(16)));
const hex1 = map(u8, toByte, hex);
const hex2 = map(u8, toByte2, manyN(2, hex));
const rgb1 = map(Rgb, toStruct(Rgb), manyN(3, hex1));
const rgb2 = map(Rgb, toStruct(Rgb), manyN(3, hex2));
const rgb = combine(.{
    ascii.char('#'),
    oneOf(.{
        rgb2,
        rgb1,
    }),
});

pub fn main() !void {
    var loops: usize = 20_000_000_000;
    const loop_ptr: *volatile usize = &loops;

    var n: usize = 0;

    const allocator = std.heap.page_allocator;
    const start = std.time.nanoTimestamp();

    while (n < loop_ptr.*) : (n += 1) {
        const a = rgb("#aabbcc").?.value;
        // const a = (try rgb(allocator, "#aabbcc")).value;
        std.math.doNotOptimizeAway(a);
    }
    const end = std.time.nanoTimestamp();
    const stdout = std.io.getStdOut().writer();

    try stdout.print("{} ns\n", .{(end - start)});
}
```

```
Master: 9274738222 ns
Branch: 4647510447 ns
```

I wouldn't claim that this branch is actually 2x faster than master, but instead I will say that this benchmark is not good enough to get a real idea as to the performance of mecha.

2021-02-23 22:42 UTC, data-man commented
Some thoughts:

1. Don't use errors. It has a cost. Returns `null` for allocations errors.
2. 
```zig
const use_allocs = @hasDecl(root, "mecha_uses_allocators");
```
or

3. change inner funcs to 
```zig
fn func(params: anytype) ?Res { //or other optional type
    if (meta.trait.isTuple(params) and ...) {//checks if params[0] is allocator
       // code with allocator
       // use params[1] as input
    } else {
       // code without allocator
    }
}
```
Not sure that it will work, just PoC. :)

2021-02-24 15:17 UTC, Hejsil commented
>     1. Don't use errors. It has a cost. Returns `null` for allocations errors.

I would very much like it if you elaborated and provided some clear evidence that they have a "cost" (I'm not even sure what kind of cost you are talking about, but I'm assuming you mean runtime cost). Both `Error!Result(usize)` and `?Result(usize)` have the same size on my system, so the same amount of data is being copied around. Try it for yourself:
```zig
pub fn Result(comptime T: type) type {
    return struct { v: T, r: []const u8 };
}

test "" {
    @compileLog(@sizeOf(?Result(usize)));
    @compileLog(@sizeOf(anyerror!Result(usize)));
}
```

```
| 32
| 32
./test.zig:6:5: error: found compile log statement
    @compileLog(@sizeOf(?Result(usize)));
    ^
./test.zig:7:5: error: found compile log statement
    @compileLog(@sizeOf(anyerror!Result(usize)));
```

Looking at the assembly of branching on error vs optional is a little hard to compare, but I made a [godbolt link here](https://godbolt.org/z/PeWTTd) so you can play around with this too. In my simple example, branching on error produces less code (but we are at the mercy of the optimizer here). Hard to say if there is an actual just, but in theory `try` vs `orelse return null` should produce virtually identical code.

I'm gonna merge this. If you can provide a clear benchmark of a complicate parser that shows clearly, without question, that this change has degraded the performance of mecha then I'm willing to consider reverting this. As of now, there is no clear evidence for this.

2021-02-24 15:18 UTC, merged