Track parser position and "token" spans
Hejsil/mecha pull request #74
Opened 2024-11-05 16:57 UTC by joelreymont

2024-11-05 18:16 UTC, joelreymont commented
It builds fine on my laptops with the latest version of Zig.

2024-11-06 08:24 UTC, Hejsil requested changes

2024-11-06 08:24 UTC, Hejsil commented on mecha.zig
> +        }
I'd put this as a function on the `Error` (`Fail`) struct. It doesn't make much sense to report errors on none error results.

Also, it's worth considering what this function is actually for. Right now, it seems like a function for developer debugging. It does not report anything useful for users of the program.

2024-11-06 08:24 UTC, Hejsil commented on mecha.zig
> +    fmt.ParseIntError;
Don't add another error to this set unless you have a good reason. Most of the time, parsers should catch errors from `std.fmt` and return `.{ .err = .{ ... } }` so that the parser can recover and continue parsing.

2024-11-06 08:24 UTC, Hejsil commented on mecha.zig
> +                            .err => return Res.failWith(sep, pos),
I don't see the `failWith` function adding much. I'd just do this everywhere instead and remove it:

```suggestion
                            .err => |e| return Res.fail(e.loc, e.pos + pos),
```

2024-11-06 08:24 UTC, Hejsil commented on mecha.zig
> +        };
Would it be possible for us just to return position and value?

```suggestion
        const Pass = struct {
            pub const Value = T;

            value: T,
            pos: usize,
        };
```

Pretty sure this has all the information need

2024-11-06 08:24 UTC, Hejsil commented on mecha.zig
> +            }
There's a lot of places where you switch on the result, but don't unpack the `ok` value. You then need to do `r.ok` later. Instead, do this:

```suggestion
            const r = switch (try parser.parse(allocator, str)) {
                .ok => |ok| ok,
                .err => |e| return e,
            };
```

2024-11-06 08:24 UTC, Hejsil commented on mecha.zig
> +            return std.meta.stringToEnum(Enum, str) orelse error.OtherError;
Don't return `OtherError` here. `OtherError` means an error that cannot be recovered from by `mecha` and will just be bubbled up. Maybe it should be called something else, but no need to do that now.

2024-11-06 08:24 UTC, Hejsil commented on mecha.zig
> +/// const digits = oneOf(.{ .ok = .{ combine(.{ digit_10, ref(digitsRef) }), digit_10 } });
This isn't right

2024-11-06 08:34 UTC, joelreymont commented on example/json.zig
> +    try json.fail(testing.allocator, s, pos);
The tracking of error position in nested parsers works, though, as I wrote a test for that. 

I haven’t investigated why the json parsers all fail at 0 but `err(‘ ‘)` requires a 1.

2024-11-06 08:38 UTC, joelreymont commented on mecha.zig
> +        }
You are right, I will remove it.

2024-11-06 08:39 UTC, joelreymont commented on mecha.zig
> +    fmt.ParseIntError;
Will fix!

2024-11-06 08:40 UTC, joelreymont commented on mecha.zig
> +                            .err => return Res.failWith(sep, pos),
A type error was the reason for this change. I’ll try your suggestion and update this conversation.

2024-11-06 08:45 UTC, joelreymont commented on mecha.zig
> +        };
Knowing the span of a token should make for better error reporting during type-checking. For example, enabling one to highlight the whole “token”. Just tracking position won’t do it.

2024-11-06 08:52 UTC, joelreymont commented on mecha.zig
> +            return std.meta.stringToEnum(Enum, str) orelse error.OtherError;
What should I return then? 

I need to know that there was an error so that I convert this to a parser failure.

2024-11-06 08:52 UTC, joelreymont commented on mecha.zig
> +/// const digits = oneOf(.{ .ok = .{ combine(.{ digit_10, ref(digitsRef) }), digit_10 } });
Will fix

2024-11-06 08:54 UTC, joelreymont commented on mecha.zig
> +        };
I’ll add tests to check. The parent parser should update the span start for results returned by child parsers.

2024-11-06 09:02 UTC, joelreymont commented on mecha.zig
> +            return std.meta.stringToEnum(Enum, str) orelse error.OtherError;
So just implement the change that you suggested and keep the error, right?

2024-11-06 09:23 UTC, Hejsil commented on mecha.zig
> +            return std.meta.stringToEnum(Enum, str) orelse error.OtherError;
> So just implement the change that you suggested and keep the error, right?

No sorry, you still need to return something other than `OtherError`. Maybe `error.ConversionFailed`

2024-11-06 10:29 UTC, joelreymont commented on example/json.zig
> +    try err(1, " ");
The counter-example.

2024-11-06 10:30 UTC, joelreymont commented on example/json.zig
> +    try json.fail(testing.allocator, s, pos);
The counter-example is at like 1374.

2024-11-06 15:28 UTC, joelreymont commented on mecha.zig
> +        };
Unfortunately, my PR is not gonna work for token span tracking.

No span tracking is possible unless parsers take a context and this context is then propagated to child parsers (like in PR #73).

Only error position tracking is possible in the current version of the code since errors bubble up but only values of successful parses are stored and the rest of the result data discarded.

2024-11-07 06:49 UTC, closed without merging